"use strict";
function __export(m) {
    for (var p in m) if (!exports.hasOwnProperty(p)) exports[p] = m[p];
}
Object.defineProperty(exports, "__esModule", { value: true });
/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */
__export(require("../generated-wrappers/coordinator"));
__export(require("../generated-wrappers/coordinator_registry"));
__export(require("../generated-wrappers/lib_constants"));
__export(require("../generated-wrappers/lib_coordinator_approval"));
__export(require("../generated-wrappers/lib_coordinator_rich_errors"));
__export(require("../generated-wrappers/lib_e_i_p712_coordinator_domain"));
//# sourceMappingURL=wrappers.js.map